repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      # Python-specific
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements

  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.12.6
    hooks:
      - id: typos
        args: []

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        description: Format python code with `ruff`.
        entry: uv run ruff format src
        language: system
        files: \.py$
        pass_filenames: false
      - id: ruff-check
        name: ruff
        description: Check python code with `ruff`.
        entry: uv run ruff check --fix --exit-non-zero-on-fix src
        language: system
        files: \.py$
        pass_filenames: false
      - id: mypy-check
        name: mypy
        description: Check python code with `mypy`.
        entry: uv run mypy src
        language: system
        files: \.py$
        pass_filenames: false
